# -*- coding: utf-8 -*-
"""Students_Performance_by_Amarachi_Ike.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1myxy21ticp3B74HrNaQKWndhRAUn-z35
"""

import pandas as pd

Students_Performance=pd.read_csv("/content/StudentsPerformance.csv")

Students_Performance.shape

# This code is used to get the first n rows
Students_Performance.head()

Students_Performance.tail()

#This code is used to view some basic statistical details.
Students_Performance.describe

print(Students_Performance.columns)

Students_Performance['writing score']

Students_Performance['math score']

Students_Performance['reading score']

Students_Performance['math score'].dtype

Students_Performance['gender'].dtype
#object type

Students_Performance['math score'].values

Students_Performance['gender'].value_counts

Students_Performance['math score'].std()

Students_Performance['reading score'].std()

Students_Performance['writing score'].std()

Students_Performance['gender'].unique()

Students_Performance['race/ethnicity'].unique()

print(Students_Performance['lunch'].unique())

print(Students_Performance['gender'].unique())

print(Students_Performance['race/ethnicity'].unique())

Students_Performance['math score'].median()

Students_Performance['reading score'].median()

Students_Performance['writing score'].median()

Students_Performance.gender.value_counts()

Students_Performance.groupby(['gender'])

print(Students_Performance.groupby(['gender']))

Students_Performance.groupby(['gender']).mean()

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import seaborn as sns
Students_Performance = pd.read_csv("/content/StudentsPerformance.csv", index_col=0)
Students_Performance.head()

Students_Performance['math score'].value_counts().head(10).sort_index().plot.bar()

Students_Performance['writing score'].value_counts().head(10).sort_index().plot.bar()

Students_Performance['reading score'].value_counts().head(10).plot.bar()

Students_Performance[Students_Performance['math score'] < 100]['math score'].value_counts().sort_index().plot.line()

#pandas plot
Students_Performance[Students_Performance['writing score'] < 100]['writing score'].value_counts().sort_index().plot.line()

#pandas plot
Students_Performance[Students_Performance['reading score'] < 100]['reading score'].value_counts().sort_index().plot.line()

Students_Performance['math score'].value_counts().head(10).plot.bar()

sns.countplot(Students_Performance['math score'])

Students_Performance['writing score'].value_counts().head(10).plot.bar()

sns.countplot(Students_Performance['writing score'])

# pandas plot
Students_Performance[Students_Performance['math score'] < 100]['math score'].value_counts().sort_index().plot.line()

sns.kdeplot(data=Students_Performance, x='math score')